cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end

  resources :cat_rental_requests  
end

cats_99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_99/app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = [
    "red",
    "blue",
    "yellow",
    "green",
    "purple"
  ].freeze


  validates :birth_date, :name, :description, presence: true
  validates :sex, presence: true, inclusion: { in: %w(M F) }
  validates :color, presence: true, inclusion: COLORS



  def age
    Date.today.year - birth_date.year
  end

  has_many :cat_rental_requests,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy
end

cats_99/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, presence: true, inclusion: { in: %w(APPROVED PENDING DENIED) }
  validate :does_not_overlap_approved_request

  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat

  def overlapping_requests
    CatRentalRequest.select('*').where("end_date > #{self.start_date}" )
  end

  def overlapping_approved_requests
    cat_rentals = overlapping_requests
    cat_rentals.select { |cat_rentals| cat_rentals.cat_id = self.cat_id }
  end

  def does_not_overlap_approved_request
    if !overlapping_approved_requests.empty?
      errors.add(:rental_conflict, 'Cat cannot be rented. Suckaaaaa')
    end
  end

end

cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats_99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    @cat_rental = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental = CatRentalRequest.new(cat_rental_params)
    if @cat_rental.save
      render json: @cat_rental
    else
      render json: @cat_rental.errors.full_messages
    end
  end

  private

  def cat_rental_params
    params.require(:cat_rental).permit(:cat_id, :start_date, :end_date)
  end

end

cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render json: @cat
    else
      render json: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
private

def cat_params
  params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
end

end

cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_99/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

cats_99/app/helpers/cats_helper.rb
module CatsHelper
end

cats_99/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">

  <li><label for="cat_id">Cats</label></li>
  <select name="cat_rental[cat_id]">
    <option value="">-- select a cat --</option>
    <% @cats.each do |cat|  %>
     <option value="<%=cat.id%>" ><%=cat.name%>, <%=cat.age%>, <%= cat.color %>, <%= cat.description %></option>
    <% end %>

  </select><br>

  <li><label for="start_date">Start Date</label></li>
  <input type="date" name="cat_rental[start_date]"><br>

  <li><label for="end_date">End Date</label></li>
  <input type="date" name="cat_rental[end_date]"><br>

<input type="submit" value="Order Cat">
</ul>
</form>

cats_99/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat.id)  %>
<% else %>
  <% action_url = cats_url %>
<% end %>
<form action="<%= action_url %>" method="post">
  <ul>
  <% if action == :edit %>
    <input type ="hidden" name="_method" value="PATCH">
  <% end %>

  <li><label for="name">Name</label></li>
  <input type="text" name="cat[name]" value= <%=cat.name%> ></br>

  <li><label for="sex">Sex</label></li>
  <input type="radio" name="cat[sex]" value='M' <%="checked" if cat.sex == "M"%>>M
  <input type="radio" name="cat[sex]" value='F' <%="checked" if cat.sex == "F"%>>F<br>

  <li><label for="birth_date">Birthdate</label></li>
  <input type="date" name="cat[birth_date]" value= <%=cat.birth_date%>><br>

  <li><label for="color">Color</label></li>
  <select name="cat[color]">
    <option value="">-- select a color --</option>
    <%Cat::COLORS.each do |color|  %>
     <option value="<%=color%>" <%= cat.color == color ? "selected" : "" %>><%=color%></option>
    <% end %>

  </select><br>

  <li><label for="description">Description</label></li>
  <textarea name="cat[description]" rows="8" cols="80">
    <%=cat.description%>
  </textarea><br>

<input type="submit" value= "<%= action == :edit ? 'Update cat' : 'Add cat'%>">
</ul>
</form>

cats_99/app/views/cats/edit.html.erb
<%= render "form", action: :edit, cat:@cat %>

cats_99/app/views/cats/index.html.erb
<h1>Cats</h1>

<% @cats.each do |cat| %>
  <li><%= link_to "#{cat.name}", cat_url(cat) %></li>
<% end %>

cats_99/app/views/cats/new.html.erb
<%= render "form", action: :new, cat:@cat  %>

cats_99/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th colspan = "2"><%= @cat.name %> attributes</th>
  </tr>
  <tr>
    <th>Birthdate</th>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <th>Color</th>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <th>Sex</th>
    <td><%= @cat.sex %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @cat.description %></td>
  </tr>
</table>

cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>